name: Hello, Github Action!
on: [push]
jobs: 
  Hello:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5 
          with:
            python-version: 'pypy3.9' 
        - run: python -v